name: Deploy to Lighweight Cloud

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 浅克隆，加快检出速度

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.next/server
            ${{ github.workspace }}/.next/static
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies (with cache)
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          if [ -f package-lock.json ]; then
            npm ci --prefer-offline --no-audit --progress=false
          else
            npm install --prefer-offline --no-audit --progress=false
          fi

      - name: Generate package.json MD5
        run: |
          echo "PACKAGE_JSON_MD5=$(md5sum package.json | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "Package.json MD5: $(md5sum package.json | cut -d' ' -f1)"

      - name: Build project
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          export NEXT_TELEMETRY_DISABLED=1
          npm run build -- --no-lint

      - name: Optimize build output
        run: |
          echo "Optimizing build output..."
          # 删除不需要部署的文件
          rm -rf .git .github node_modules/.cache

      - name: Copy files to server via rsync over SSH
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude 'node_modules' --exclude '.git' --exclude '.github' --exclude '.next/cache'
          path: ./*
          remote_path: /home/ubuntu/my-blog
          remote_host: 43.139.236.77
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Smart Dependencies Installation and Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.139.236.77
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/my-blog
            
            echo "==== 检查Node.js版本 ===="
            node --version
            npm --version
            
            # 检查package.json是否变更
            CURRENT_MD5="${{ env.PACKAGE_JSON_MD5 }}"
            CACHE_FILE="/home/ubuntu/.my-blog-package-cache"
            NEED_INSTALL=false
            
            echo "==== 检查依赖是否需要更新 ===="
            if [ -f "$CACHE_FILE" ]; then
              CACHED_MD5=$(cat "$CACHE_FILE")
              echo "缓存的MD5: $CACHED_MD5"
              echo "当前的MD5: $CURRENT_MD5"
              
              if [ "$CACHED_MD5" != "$CURRENT_MD5" ]; then
                echo "package.json已变更，需要重新安装依赖"
                NEED_INSTALL=true
              else
                echo "package.json未变更，跳过依赖安装"
                NEED_INSTALL=false
              fi
            else
              echo "未找到缓存文件，首次安装依赖"
              NEED_INSTALL=true
            fi
            
            # 检查node_modules是否存在
            if [ ! -d "node_modules" ]; then
              echo "node_modules目录不存在，需要安装依赖"
              NEED_INSTALL=true
            fi
            
            # 安装或跳过依赖
            if [ "$NEED_INSTALL" = true ]; then
              echo "==== 安装/更新依赖 ===="
              # 清理旧的依赖
              rm -rf node_modules package-lock.json 2>/dev/null || true
              
              # 使用npm install进行全新安装，优化安装速度
              export NODE_OPTIONS="--max-old-space-size=4096"
              if npm install --production=false --prefer-offline --no-audit --no-fund --progress=false; then
                echo "依赖安装成功"
                # 保存MD5到缓存文件
                echo "$CURRENT_MD5" > "$CACHE_FILE"
              else
                echo "依赖安装失败，退出"
                exit 1
              fi
            else
              echo "==== 跳过依赖安装 ===="
              echo "依赖未变更，使用现有依赖"
            fi
            
            echo "==== 检查是否需要重新构建 ===="
            BUILD_NEEDED=true  # 总是构建，确保有构建产物
            
            echo "==== 重新构建项目 ===="
            # 清除旧的构建产物和缓存
            rm -rf .next 2>/dev/null || true
            
            # 创建 .eslintrc.json 文件以禁用导致构建失败的规则
            cat > .eslintrc.json << 'EOF'
            {
              "extends": "next/core-web-vitals",
              "rules": {
                "react/no-unescaped-entities": "off",
                "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
                "@next/next/no-img-element": "warn"
              }
            }
            EOF
            
            # 强制构建，忽略 lint 错误
            export NODE_OPTIONS="--max-old-space-size=4096"
            export NEXT_TELEMETRY_DISABLED=1
            if npm run build -- --no-lint; then
              echo "构建成功"
            else
              echo "构建失败，尝试使用 SKIP_ESLINT=1 重试"
              export SKIP_ESLINT=1
              export NEXT_TELEMETRY_DISABLED=1
              if npm run build -- --no-lint; then
                echo "构建成功（跳过ESLint）"
              else
                echo "构建再次失败，退出部署"
                exit 1
              fi
            fi
            
            echo "==== 构建完成，检查构建结果 ===="
            if [ ! -d ".next/static" ] || [ ! -d ".next/server" ]; then
              echo "构建产物不完整，退出部署"
              exit 1
            fi
            
            ls -la .next/ 2>/dev/null || echo ".next目录内容检查失败"

      - name: Smart PM2 Service Management
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.139.236.77
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/my-blog
            
            # 首先检查构建是否成功
            if [ ! -d ".next/static" ] || [ ! -d ".next/server" ]; then
              echo "❌ 构建产物不存在或不完整，跳过服务启动"
              exit 1
            fi
            
            echo "==== 检查 PM2 安装状态 ===="
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 未安装，尝试安装"
              if npm install -g pm2; then
                echo "PM2 安装成功"
              else
                echo "PM2 安装失败，尝试使用 sudo"
                sudo npm install -g pm2
              fi
            fi
            
            echo "==== 智能重启应用 ===="
            if pm2 show my-blog > /dev/null 2>&1; then
              echo "应用已存在，执行重载"
              if pm2 reload my-blog; then
                echo "应用重载成功"
              else
                echo "重载失败，尝试重启"
                pm2 restart my-blog
              fi
            else
              echo "应用不存在，启动新应用"
              pm2 start npm --name "my-blog" -- start
            fi
            
            echo "==== 等待应用稳定 ===="
            sleep 5
            
            # 保存PM2配置
            pm2 save > /dev/null 2>&1 || echo "PM2配置保存失败"
            
            # 检查应用是否正常启动
            if ! pm2 show my-blog | grep -q "online"; then
              echo "❌ 应用启动失败，查看日志"
              pm2 logs my-blog --lines 20
              exit 1
            fi

      - name: 应用状态检查
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.139.236.77
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "==== PM2 应用状态 ===="
            pm2 list
            
            echo "==== 应用端口检查 ===="
            # 增加重试次数，有时应用启动需要一点时间
            MAX_RETRIES=5
            RETRY_COUNT=0
            PORT_LISTENING=false
            
            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if lsof -i:3000 > /dev/null 2>&1; then
                echo "✅ 端口 3000 正常监听"
                PORT_LISTENING=true
                break
              else
                RETRY_COUNT=$((RETRY_COUNT+1))
                echo "⚠️ 端口 3000 未监听，等待 5 秒后重试 ($RETRY_COUNT/$MAX_RETRIES)..."
                sleep 5
              fi
            done
            
            if [ "$PORT_LISTENING" = false ]; then
              echo "❌ 端口 3000 最终未被监听"
              pm2 logs my-blog --lines 20
              exit 1
            fi
            
            echo "==== HTTP 访问测试 ===="
            for i in {1..5}; do
              echo "尝试 $i/5..."
              if curl -f -s -I http://localhost:3000 > /dev/null; then
                echo "✅ HTTP 访问成功！"
                break
              else
                echo "❌ HTTP 访问失败，等待 5 秒后重试..."
                if [ $i -eq 5 ]; then
                  echo "HTTP访问最终失败，查看日志："
                  pm2 logs my-blog --lines 20
                  exit 1
                fi
                sleep 5
              fi
            done
            
            echo "==== HTTPS 访问测试 ===="
            if curl -f -s -I https://rshan.cc > /dev/null; then
              echo "✅ HTTPS 访问成功！"
            else
              echo "⚠️ HTTPS 访问失败（可能是SSL配置问题）"
              # HTTPS 失败不视为构建失败，因为可能是 SSL 配置问题
            fi
            
            echo "==== 部署完成 ===="
            echo "🎉 应用已成功部署并启动！"
            
            # 显示缓存状态
            CACHE_FILE="/home/ubuntu/.my-blog-package-cache"
            if [ -f "$CACHE_FILE" ]; then
              echo "📦 当前依赖缓存MD5: $(cat $CACHE_FILE)"
            fi
            
            # 记录构建性能指标
            echo "==== 记录构建性能指标 ===="
            bash scripts/build-performance.sh || echo "性能记录脚本执行失败"