name: Deploy to Lighweight Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files to server via rsync over SSH
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude 'node_modules' --exclude '.git'
          path: ./*
          remote_path: /home/ubuntu/my-blog
          remote_host: 43.139.236.77
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Start/Reload PM2 Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.139.236.77
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/my-blog
            # 检查 PM2 是否已安装
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 未安装，尝试使用 sudo 安装"
              sudo npm install -g pm2 || echo "PM2 安装失败，但继续执行"
            fi
            # 启动或重载应用
            pm2 reload my-blog || pm2 start npm --name "my-blog" -- start

      - name: 应用状态检查
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.139.236.77
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "==== PM2 应用状态 ===="
            pm2 list
            echo "==== 应用端口检查 ===="
            lsof -i:3000 || echo "端口 3000 未被监听"
            echo "==== 应用访问测试 ===="
            curl -I http://localhost:3000 || echo "无法访问 3000 端口"